## 第八章 异常处理

​	Go语言使用error来处理错误，用panic和recover来处理异常。

### 8.1 error

​	error是一种内建的接口类型，error的接口就声明了一个Error()方法，任何实现了该方法的结构体都可以作为error来使用。error的实例代表一种异常状态，Error()方法用于描述该异常状态，值为nil的error代表没有异常。

> 标准库提供了两种创建error的方法：
>
> - `errors.New()`
>
> - `fmt.Errorf`
>
>   `error.New()`的实现就只是构造了一个`errorString`实例就返回了。
>
>   `fmt.Errorf()`只是对`error.New()`的简单封装，适用于需要格式化输出错误字符串的场景。
>
>   由于`fmt.Errorf()`在生成格式化字符串时需要遍历所有字符串，所以性能会有所损失。
>
> 异常处理：对error而言，有检查错误和传递错误
>
> ​					最常见的检查error的方式是与nil值进行比较。
>
> ​					收到一个error，一般需要加上一些上下文信息再把error继续往上抛。

#### 链式error

​	error在函数传递时，上下文信息好像链条一样把各个error连接起来。

​	`fmt.Errorf()`格式化动词%w用于生成wrapError实例，wrapError与errorString相比，额外实现了Unwrap()接口，用于返回原始的error。

### 8.2 defer

​	defer语句用于延迟函数的调用，常用于关闭文件描述符、释放锁等资源释放场景。

​	defer语句采用后进先出的设计，类似栈。

​	函数中任何一个return语句、panic语句均会触发延迟函数。

#### 使用场景

> - 释放资源
> - 流程控制
> - 异常处理

#### 行为规则

> defer只能作用于函数和函数调用。
>
> - 1.延迟函数的参数在defer语句出现时就已经确定了。
>
> - 2.延迟函数按后进先出的顺序执行。
> - 3.延迟函数可能操作主函数的具名返回值。

### 8.3 panic

​	对于危险操作，比如内存越界访问等，go程序经常显式地触发panic，提前结束程序运行。支持recover()消除panic。

​	panic()是一个内置函数，接受任意类型参数，参数将在程序崩溃时通过另一个内置函数print打印出来。如果程序返回过途中任意一个defer函数执行了recover()，那么该参数也是recover()的返回值。

> panic会递归执行协程中所有的defer,与函数正常退出时的执行顺序一样；
>
> panic不会处理其他协程中的panic；
>
> 当前协程中的defer处理完成后，触发程序退出。

### 8.4 recover

​	内置函数recover()用于消除panic并使程序恢复正常。

​	recover()也是一个内置函数，recover()的返回值就是panic()的参数。

​	recover()必须直接位于defer函数中才有效。

​	recover()可以消除本函数产生或收到的panic，上游函数感知不到panic的发生。